
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>FordSpawnerQuest</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>Libs\MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="BoneLib">
      <HintPath>Libs\BoneLib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSLZ.Marrow">
      <HintPath>Libs\Il2CppSLZ.Marrow.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>Libs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
